# Generated by Django 5.0.6 on 2026-06-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'equipment_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена покупки')),
                ('warranty_period', models.IntegerField(blank=True, help_text='Месяцев', null=True, verbose_name='Гарантийный срок')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('in_use', 'В использовании'), ('repair', 'В ремонте'), ('written_off', 'Списано'), ('lost', 'Утеряно')], default='available', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/photos/', verbose_name='Фотография')),
                ('document', models.FileField(blank=True, null=True, upload_to='equipment/documents/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.category', verbose_name='Категория')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Подразделение')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Единица оборудования',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment_equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('returned', 'Возвращено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('document', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Документ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Создатель')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_assignments', to='departments.department', verbose_name='Откуда')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_assignments', to='accounts.customuser', verbose_name='Отдающий')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_assignments', to='departments.department', verbose_name='Куда')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_assignments', to='accounts.customuser', verbose_name='Принимающий')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Назначение оборудования',
                'verbose_name_plural': 'Назначения оборудования',
                'db_table': 'equipment_assignment',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'db_table': 'equipment_accessory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('status_changed', 'Статус изменён'), ('assigned', 'Назначено'), ('returned', 'Возвращено'), ('deleted', 'Удалено')], max_length=20, verbose_name='Действие')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'db_table': 'equipment_equipmentlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['inventory_number'], name='equipment_e_invento_3592e9_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['department'], name='equipment_e_departm_d9753e_idx'),
        ),
    ]
