# Generated by Django 5.0.6 on 2026-06-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('planned', 'Плановое'), ('repair', 'Ремонт'), ('inspection', 'Инспекция'), ('upgrade', 'Модернизация')], max_length=20, verbose_name='Тип обслуживания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('scheduled_date', models.DateField(verbose_name='Запланированная дата')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('document', models.FileField(blank=True, null=True, upload_to='maintenance/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Технический специалист')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживание',
                'db_table': 'maintenance_maintenance',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
