# Generated by Django 5.0.6 on 2026-06-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('report_type', models.CharField(choices=[('inventory', 'Инвентаризация'), ('movement', 'Перемещения'), ('maintenance', 'Обслуживание'), ('status', 'Статус оборудования'), ('financial', 'Финансовый')], max_length=20, verbose_name='Тип отчёта')),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('docx', 'Word'), ('pdf', 'PDF')], default='xlsx', max_length=10, verbose_name='Формат')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Файл')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'reports_report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
